version: '3.8'


services:

  eureka-server:
    container_name: gymcrm-eureka-server-container
    build:
      context: ./eureka-server
    depends_on:
      - gymcrm-db
    ports:
      - "8761:8761"

  report-microservice:
    container_name: gymcrm-report-microservice-container
    build:
      context: ./report-microservice
    depends_on:
      - gymcrm-db
    ports:
      - "8085:8085"

  main-microservice:
    container_name: gymcrm-main-microservice-container
    build:
      context: ./
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    depends_on:
      - eureka-server
      - gymcrm-db
    ports:
      - "8082:8082"

  gymcrm-db:
    container_name: gymcrm-postgres-db-container
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    container_name: gymcrm-mongodb-container
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  activemq:
    container_name: gymcrm-activemq-container
    image: apache/activemq-artemis:latest-alpine
    ports:
      - "8161:8161"
      - "61616:61616"

volumes:
  postgres-data:
  mongodb-data: