spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate-app
    username:
    password:
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true

server:
  port: 8082

springdoc:
  swagger-ui:
    enabled: true

cors:
  allowed-origins: "http://localhost:8081/swagger-ui"


jwt:
  secret: N0T_S3CR3T_B3C4USE_1T_1S_S3CR3T_TH4T_1S_4LL_Y0U_N33D
  token:
    access:
      expiration: 6000 # milliseconds -> 2 hours
    refresh:
      expiration: 172800000 # milliseconds -> 2 days

login_attempts:
    max_attempts: 3
    lock_duration: 300000 # milliseconds -> 5 minutes