spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://gymcrm-db:5432/gymcrm_prod
    username: prod_user
    password: prod_1125
    driverClassName: org.postgresql.Driver
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
    pool:
      block-if-full: true
      block-if-full-timeout: -1
      enabled: false
      idle-timeout: 30000
      max-connections: 1
  jms:
    listener:
      auto-startup: true
      max-concurrency: 10
    pub-sub-domain: false
    template:
      default-destination:
      delivery-mode: non_persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 36000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  info:
    env:
      enabled: true


server:
  port: 8082

springdoc:
  swagger-ui:
    enabled: true

cors:
  allowed-origins: "http://report-microservice:8085/api/v1"

microservices:
  report:
    url: http://report-microservice:8085/api/v1

jwt:
  secret: N0T_S3CR3T_B3C4USE_1T_1S_S3CR3T_TH4T_1S_4LL_Y0U_N33D
  token:
    access:
      expiration: 7200000 # milliseconds -> 2 hours
    refresh:
      expiration: 172800000 # milliseconds -> 2 days

login_attempts:
  max_attempts: 3
  lock_duration: 300000 # milliseconds -> 5 minutes

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

resilience4j:
  circuitbreaker:
    instances:
      cb-manage-trainer-workload: &cb-config
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 3
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
      cb-get-trainer-summary: *cb-config