jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/hibernate-app
  username: postgres
  password: slon123

jwt:
  secret: NOT SECRET

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  format_sql: true
  hbm2ddl:
    auto: update