server:
  port: 8085
  servlet:
    context-path: /api/v1
spring:
  application:
    name: report-microservice
  datasource:
    url: jdbc:h2:mem:report_database
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  activemq:
    broker-url: tcp://localhost:61616 # tcp://activemq:61616
    user: admin
    password: admin
    pool:
      block-if-full: true
      block-if-full-timeout: -1
      enabled: false
      idle-timeout: 30000
      max-connections: 1
  jms:
    listener:
      auto-startup: true
      max-concurrency: 10
    pub-sub-domain: false
    template:
      default-destination:
      delivery-mode: non_persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 36000
  data:
    mongodb:
      uri: mongodb+srv://akmalkhamidov:1125@gymcrm-report.dcefk4l.mongodb.net/?retryWrites=true&w=majority&appName=gymcrm-report
      auto-index-creation: true
      database: gymcrm-report
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "Report microservice"
    description: "Responsible to manage reports for trainer/trainings."
    version: "1.0.0"

cors:
  allowed-origins: "http://localhost:8082/api/v1/**" #"http://main-microservice:8082/api/v1/**"

eureka:
  client:
    service-url:
        defaultZone:  http://localhost:8761/eureka/ #http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
jwt:
  secret: N0T_S3CR3T_B3C4USE_1T_1S_S3CR3T_TH4T_1S_4LL_Y0U_N33D